# Generated by Django 4.2.2 on 2024-01-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_alter_tarea_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(default='No importante', max_length=100),
        ),
    ]
